[WIP] 値を取得処理の変更
YasuomiTakano/litexbrl pull request #7
Opened 2016-10-03 11:21 UTC by YasuomiTakano

※詳細は後ほど書く。

2016-10-05 05:03 UTC, nishaya commented
新しく追加したメソッドのテストは？

2016-10-05 05:05 UTC, YasuomiTakano commented
テスト書いていなかった・・・。

2016-10-05 05:21 UTC, nishaya requested changes

2016-10-05 05:21 UTC, nishaya commented on lib/litexbrl/edinet/financial_information.rb
> +          doc.namespaces.each_key do |key|
`doc.namespaces.map` で1行にまとめられるね

2016-10-05 05:21 UTC, nishaya commented on lib/litexbrl/edinet/financial_information.rb
> +            if namespaces.include?(ns)
`find_namespaces(doc) & namespaces_array` でいいような
ついでに言うと`namespaces_array` の内容が前の箇所で使っている `namespaces_array` と内容同じで、かつ意味も同じなら定数にしたい

2016-10-05 06:07 UTC, suthio commented
eachはmapで書けないか？って考えて書いてみてください。

2016-10-05 06:07 UTC, suthio commented on lib/litexbrl/edinet/financial_information.rb
> +          namespaces_array.each do |ns|
以下のようにしていったほうがいい感じしますね。

```
namespaces_array.select do |ns|
  namespaces.include? ns
end.map do |ns|
  item.map do |i|
    context_array.map |c|
      "//xbrli:xbrl/#{ns}:#{i}[starts-with(@contextRef,'#{c}_') and contains(@contextRef, '#{context_ref_name}')]"
    end
  end
end.flatten
```

2016-10-05 06:07 UTC, suthio commented on lib/litexbrl/edinet/financial_information.rb
> +          xpath_array.each do |x|
mapとselectで書いた方がテストしやすく動作もわかりやすいはずです。

2016-10-05 06:07 UTC, suthio commented on lib/litexbrl/edinet/financial_information.rb
> +          namespaces_array.each do |ns|
mapとselect使って書きましょう。

2016-10-06 06:50 UTC, YasuomiTakano commented
@nishaya 
テストはdiffが大きくなる関係で別のプルリクで対応致します。

2016-10-06 07:23 UTC, YasuomiTakano commented on lib/litexbrl/edinet/financial_information.rb
> +          doc.namespaces.each_key do |key|
`doc.namespaces.keys.map` という形で修正しました。

2016-10-06 08:01 UTC, YasuomiTakano commented on lib/litexbrl/edinet/financial_information.rb
> +          namespaces_array.each do |ns|
以下のような形で修正しました。
```
xpath_array = (find_namespaces(doc) & namespaces_array).map do |ns|
            item.map do |i|
              context_array.map do |c|
                "//xbrli:xbrl/#{ns}:#{i}[starts-with(@contextRef,'#{c}_') and contains(@contextRef, '#{context_ref_name}')]"
              end
            end
          end.flatten
```

2016-10-06 08:23 UTC, YasuomiTakano commented on lib/litexbrl/edinet/financial_information.rb
> +          namespaces_array.each do |ns|
以下のような処理に致しました。

```
(find_namespaces(doc) & namespaces_array).map do |ns|
  find_value_specified_id(doc, id) do |id|
    "//xbrli:xbrl/xbrli:context#{id}/xbrli:scenario/#{ns}:explicitMember[@dimension='jpcrp_cor:OperatingSegmentsAxis']"
  end
end.flatten
```

2016-10-07 04:41 UTC, YasuomiTakano commented on lib/litexbrl/edinet/financial_information.rb
> +            if namespaces.include?(ns)
報告書の情報かセグメント情報かで今後違うものを指定する可能性があるので、ここは変数で持っておこうかと思います。

2016-10-07 04:57 UTC, suthio commented
@YasuomiTakano テストも含めたPRの方がいいかなーって思います。
テストコードあると理解進みやすいので。
テストコードありでもう一度ください。

2016-10-07 05:02 UTC, suthio commented on lib/litexbrl/edinet/financial_information.rb
> +        def find_value_jp_cor_segment(doc, item, context_ref_name, context, context_consolidation)
find_value_jp_corと同じような処理とかなっているので、共通処理した方がいいですね。

2016-10-07 05:02 UTC, suthio commented on lib/litexbrl/edinet/financial_information.rb
> +        def find_value_reportable_segments_member(doc, id)
ここもうまいこと共通化できそうですね。

2016-10-07 05:03 UTC, suthio commented on lib/litexbrl/edinet/financial_information.rb
> +        def find_value_jp_cor(doc, item, context, context_consolidation)
実はRubyではfindじゃなくてselectかもしれないです。

2016-10-11 06:01 UTC, YasuomiTakano commented on lib/litexbrl/edinet/financial_information.rb
> +        def find_value_jp_cor(doc, item, context, context_consolidation)
本家のTDnetの方が `find` 使ってしまっている場合っていかが致しましょうか？

2016-10-11 07:38 UTC, suthio commented on lib/litexbrl/edinet/financial_information.rb
> +        def find_value_jp_cor(doc, item, context, context_consolidation)
TDnetってクロールしたサイトなんじゃないですか？

2016-10-12 01:55 UTC, YasuomiTakano commented on lib/litexbrl/edinet/financial_information.rb
> +        def find_value_jp_cor(doc, item, context, context_consolidation)
TDnet : 決算短信 : litexbrlに最初から実装されている方
EDINET : 有価証券報告書,四半期報告書 : 僕がlitexbrlに追加で実装している方

なので、TDnetの方で最初から実装されているメソッドに名前を合わせたほうが良いかなと思っているのですがいかがですかね？？

2016-10-12 02:31 UTC, suthio commented on lib/litexbrl/edinet/financial_information.rb
> +        def find_value_jp_cor(doc, item, context, context_consolidation)
あー、今の実装に合わせる感じなんですね。
同じような実装だったら一旦、合わせたほうが良さそうです。

2016-10-12 02:40 UTC, YasuomiTakano commented on lib/litexbrl/edinet/financial_information.rb
> +        def find_value_jp_cor(doc, item, context, context_consolidation)
ありがとうございます。
今回は `find` で対応します。

2016-10-12 04:51 UTC, YasuomiTakano commented
クラス分けに関してはこちらのIssueで対応します。
https://github.com/YasuomiTakano/litexbrl/issues/8

2016-10-13 02:10 UTC, suthio commented on lib/litexbrl/edinet/financial_information.rb
> +        def find_value(xpath_array, doc)
こういうところのメソッド単位のテストも書いておいたほうがいいと思います

2016-10-13 02:10 UTC, suthio commented on spec/edinet/security_report_spec.rb
> +
パーサーについてはメソッド単位のテストにおける恩恵が大きいのでテストを書いていきましょう。

2016-10-13 10:34 UTC, nishaya commented
@YasuomiTakano `9449_fy.xbrl` とか、そのままリポジトリに上げるのはマズいんじゃないかな？

2016-10-13 10:53 UTC, suthio commented on lib/litexbrl/edinet/security_report.rb
> -        # binding.pry
消したほうがよさそうですね。

2016-10-13 10:53 UTC, suthio commented on spec/edinet/financial_information_spec.rb
> +            let(:result_array){['<xbrldi:explicitMember dimension="jpcrp_cor:OperatingSegmentsAxis">jpcrp040300-q2r_E05041-000:InternetInfrastructureReportableSegmentsMember</xbrldi:explicitMember>',
配列、改行した方が見やすそうですね

2016-10-13 10:53 UTC, suthio commented on spec/edinet/financial_information_spec.rb
> +              expect(FinancialInformation.send(:find_namespaces, doc("#{dir}/9449_q.xbrl"))).to match_array namespaces_array
Factorygialとかでテストデータ作ってあげてテストした方が見やすいテストになりそうですね。
本物のデータじゃなくて、偽物のわかりやすいテストデータ作るとわかりやすいかもです。

2016-10-13 10:54 UTC, YasuomiTakano commented on lib/litexbrl/edinet/security_report.rb
> -        # binding.pry
今はもう消えております！

2016-10-13 11:12 UTC, YasuomiTakano commented on spec/edinet/financial_information_spec.rb
> +            let(:result_array){['<xbrldi:explicitMember dimension="jpcrp_cor:OperatingSegmentsAxis">jpcrp040300-q2r_E05041-000:InternetInfrastructureReportableSegmentsMember</xbrldi:explicitMember>',
修正しました！

2016-10-14 02:17 UTC, YasuomiTakano commented on spec/edinet/financial_information_spec.rb
> +              expect(FinancialInformation.send(:find_namespaces, doc("#{dir}/9449_q.xbrl"))).to match_array namespaces_array
ダミーのXBRLファイルに編集しました。

2016-10-14 02:25 UTC, suthio commented on lib/litexbrl/edinet/security_report.rb
> -        # binding.pry
消えてます？

2016-10-14 02:25 UTC, suthio commented on spec/data/edinet/quarter.xbrl
> +<?xml version="1.0" encoding="UTF-8"?>
このファイル、きちんとインデントされていた方が見やすいと思います。
Mustではないと思いますが、個人的にはコメントとか書いてあったほうがわかりやすいなーって思いました。

2016-10-14 02:25 UTC, suthio commented on spec/edinet/financial_information_spec.rb
> +              expect(FinancialInformation.send(:find_namespaces, doc("#{dir}/quarter.xbrl"))).to match_array namespaces_array
このメソッドのテストのためだけのXMLとかがあってもいいような気がしています。
1つのXBRLだけだとわかりずらいと思うので。

2016-10-14 04:32 UTC, YasuomiTakano commented on lib/litexbrl/edinet/security_report.rb
> -        # binding.pry
きえてませんか？？？
少なくとも、消してプッシュしましたが・・・！
たぶん以下の状態を見る限り消えているかと思います！
https://github.com/YasuomiTakano/litexbrl/blob/find_value_edit/lib/litexbrl/edinet/security_report.rb#L22

2016-10-14 10:06 UTC, nishaya approved these changes

2016-10-17 09:42 UTC, YasuomiTakano commented on spec/data/edinet/quarter.xbrl
> +<?xml version="1.0" encoding="UTF-8"?>
インデント修正致しました。

2016-10-17 09:45 UTC, YasuomiTakano commented on spec/edinet/financial_information_spec.rb
> +              expect(FinancialInformation.send(:find_namespaces, doc("#{dir}/quarter.xbrl"))).to match_array namespaces_array
こちらに関しては出来る限り本物の四半期報告書/有価証券報告書に近いファイルの方が、本当の意味でのテストになるかと思いまして、そのままの形に近いダミーファイルにしておりますが、いかが致しましょう？？？

2016-10-17 09:54 UTC, suthio commented on spec/edinet/financial_information_spec.rb
> +              expect(FinancialInformation.send(:find_namespaces, doc("#{dir}/quarter.xbrl"))).to match_array namespaces_array
どのテストしているかわかりずらいと思うので、
テストのためだけのXMLを用意した方がいいです。
これは単体テストなので。
E2Eは別で担保してるので、単体テストのわかりやすさ、信頼性を向上させましょう。

2016-10-17 09:54 UTC, suthio commented on lib/litexbrl/edinet/security_report.rb
> -        # binding.pry
これ、消えてないですね。

2016-10-17 09:56 UTC, YasuomiTakano commented on spec/edinet/financial_information_spec.rb
> +              expect(FinancialInformation.send(:find_namespaces, doc("#{dir}/quarter.xbrl"))).to match_array namespaces_array
> E2Eは別で担保してるので、単体テストのわかりやすさ、信頼性を向上させましょう。

たしかにそうですね・・・！
編集してみます。

2016-10-18 12:11 UTC, suthio commented on spec/edinet/financial_information_spec.rb
> +              expect(FinancialInformation.send(:find_namespaces, doc("#{dir}/find_namespaces_test.xml"))).to match_array namespaces_array
わかりやすいテストって考えるんだったら、以下のようなxbrlでテストも追加するともっとわかりやすくなりそうですね。
もっとシンプルにしていいかもです。

テスト文字列
```
<?xml version='1.0' encoding='utf-8’?><xbrli:xbrl xmlns:hoge="" xmlns:fuga="" ></xbrli:xbrl>
```

テスト結果 
```
`%w(hoge fuga)`
````

2016-10-18 12:18 UTC, suthio commented on spec/edinet/financial_information_spec.rb
> +              expect(FinancialInformation.send(:find_value_jp_cor, doc("#{dir}/find_value_jp_cor_test.xml"), item, context, context_consolidation)).to eq '66707000000'
こちらもテストデータはもっとシンプルの方がいいですね。

2016-10-19 03:00 UTC, suthio commented on spec/data/edinet/find_value_jp_cor_segment_test.xml
> +<?xml version="1.0" encoding="UTF-8"?>
ここも変えた方がいいですね。
変えた方がいい場所全部書いた方がいいですか？
共通でわかると思ったんですけど。

2016-10-19 03:01 UTC, YasuomiTakano commented on spec/data/edinet/find_value_jp_cor_segment_test.xml
> +<?xml version="1.0" encoding="UTF-8"?>
いえ、再度見直してみます。
わからないところがありましたらその時に質問致します。

2016-10-19 03:05 UTC, suthio commented on spec/data/edinet/find_value_test.xml
> +<?xml version="1.0" encoding="UTF-8"?>
ここもですね。

2016-10-19 03:05 UTC, suthio commented on spec/data/edinet/find_value_jp_cor_test.xml
> +<?xml version="1.0" encoding="UTF-8"?>
ここもですね。

2016-10-19 03:05 UTC, suthio commented on spec/data/edinet/find_namespaces_test.xml
> +<xbrli:xbrl xmlns:hoge="http://hoge" xmlns:fuga="http://fuga" ></xbrli:xbrl>
`"http://hoge` は `http://example.com` とかの方がよかったかもです。

2016-10-19 04:00 UTC, suthio commented on spec/data/edinet/find_value_jp_cor_test.xml
> +<xbrli:xbrl  xmlns:xbrli="http://example.com" xmlns:jppfs_cor="http://example.com" xmlns:jppfs_cor="http://example.com">
`xmlns:jppfs_cor="http://example.com" xmlns:jppfs_cor="http://example.com` 2 つ同じ記述があるのってなにか意味があるんですか？

2016-10-19 04:00 UTC, suthio commented on spec/data/edinet/find_value_jp_cor_test.xml
> +<xbrli:xbrl  xmlns:xbrli="http://example.com" xmlns:jppfs_cor="http://example.com" xmlns:jppfs_cor="http://example.com">
`jppfs_cor` という文字列に意味がなければ別の文字に変えちゃってもいいかもしれないですね。

2016-10-19 04:00 UTC, suthio commented on spec/edinet/financial_information_spec.rb
> +            let(:item){['Result1', 'Result2', 'Result3']}
これよくわかってないんですけど、Result3だけでも想定通りの結果になるんですか？
テストから仕様がある程度わかるといいですね。

2016-10-19 05:11 UTC, YasuomiTakano commented on spec/data/edinet/find_value_jp_cor_test.xml
> +<xbrli:xbrl  xmlns:xbrli="http://example.com" xmlns:jppfs_cor="http://example.com" xmlns:jppfs_cor="http://example.com">
`'jpcrp_cor', 'jppfs_cor', 'jpdei_cor'`
の3つのうちのどれかに当てはまらないとだめですので、 `jppfs_cor` に意味はあります 🙇 
https://github.com/YasuomiTakano/litexbrl/blob/find_value_edit/lib/litexbrl/edinet/financial_information.rb#L143

2016-10-19 05:25 UTC, YasuomiTakano commented on spec/edinet/financial_information_spec.rb
> +            let(:item){['Result1', 'Result2', 'Result3']}
> Result3だけでも想定通りの結果になるんですか？
なります！

`'Result1', 'Result2', 'Result3'`のどれか一つでも引っかかればOKです。

2016-10-19 05:37 UTC, suthio commented on spec/edinet/financial_information_spec.rb
> +            let(:item){['Result1', 'Result2', 'Result3']}
result3だけで大丈夫だと思います！
あとresult4だけのテスト追加してみてください。

こんな感じですかね？
```
        describe '#find_value_jp_cor' do
          context 'japan accounting standards' do
            let(:item){['Result4']}
            let(:context){'Context'}
            let(:context_consolidation){'Consolidated'}
            example 'when you get the net sales' do
              expect(FinancialInformation.send(:find_value_jp_cor, doc("#{dir}/find_value_jp_cor_test.xml"), item, context, context_consolidation)).to eq nil
            end
          end
        end
```

2016-10-19 06:02 UTC, YasuomiTakano commented on spec/edinet/financial_information_spec.rb
> +            let(:item){['Result1', 'Result2', 'Result3']}
`Result3` と `Result4`を使うのも「なぜ3から？」という話にもなりそうでしたので `Result1` と `Result2` で対応致しました 🙇

2016-10-19 06:09 UTC, suthio commented
![ミサワ](https://d20qqtosks8wga.cloudfront.net/8/d/8d849d1f.gif)

2016-10-19 07:49 UTC, merged