[WIP] 四半期か1年かを判断するロジックの変更
YasuomiTakano/litexbrl pull request #9
Opened 2016-10-19 08:22 UTC by YasuomiTakano

## Scope
売上高などを取得する際に、現状の「四半期か1年かを判断するロジック」が原因で取得できていない件にかかる処理

## 前提

 - 現状、売上高などを取得する際は四半期か1年かを判断する必要がある。
 - 現状の判定ロジックでは、四半期報告書内に「四半期」と「1年」両方の情報が載っていいた際に「1年」の方が優先され、四半期報告書にもかかわらず、有価証券報告書と判定されてしまう。
 - 「四半期か1年かを判断するロジック」内の判定に用いている識別子を別の識別子変更して判定する必要がある。

## TODOリスト
- [x] 四半期か1年かを判断するロジックの変更
- [ ] 単体テストの確認 (未実装出会った場合は実装)

2016-10-20 02:17 UTC, suthio commented on lib/litexbrl/edinet/financial_information.rb
> +          duration = season == "FY" ? "YearDuration" : "YTDDuration"
この文字列生成部分の2行は別メソッドに切り分けて意味を持たせてあげたほうがいいかもしれないです。

2016-10-20 02:17 UTC, suthio commented on lib/litexbrl/edinet/financial_information.rb
> +          duration = season == "FY" ? "YearDuration" : "YTDDuration"
ここも上と重複しているので、共通化していいかもですね。

2016-10-20 02:17 UTC, suthio commented on lib/litexbrl/edinet/financial_information.rb
>            {
こういう連想配列のデータだったら、モデルとして定義してあげてもいいかもですね。

2016-10-20 02:17 UTC, suthio commented on spec/edinet/financial_information_spec.rb
> +               :context_duration=>"CurrentYearDuration",
fixturesとかに入れてymlに書いてもいいかもいいですね。

2016-10-20 05:35 UTC, nishaya commented on lib/litexbrl/edinet/security_report.rb
> +          season = find_season(doc)
ここで再度の `find_season(doc)`は必要？

2016-10-20 06:33 UTC, YasuomiTakano commented on lib/litexbrl/edinet/security_report.rb
> +          season = find_season(doc)
よく見直したら、 `unless season` の判定すらあまり意味がなかったので、その判定ごと消しました！

2016-10-20 09:57 UTC, YasuomiTakano commented on lib/litexbrl/edinet/financial_information.rb
>            {
ちょっと知識不足で申し訳ないのですが、これってなぜモデルのほうが良いのか教えて頂けると幸いです 🙇 
私的にはここはモデルではなくても良いのかなぁ〜と思ってます。

2016-10-20 10:03 UTC, YasuomiTakano commented on lib/litexbrl/edinet/financial_information.rb
> +          duration = season == "FY" ? "YearDuration" : "YTDDuration"
https://github.com/YasuomiTakano/litexbrl/pull/9#discussion_r84202655
こちらの対応で、メソッド切り出しましたのでそれと同時におそらく共通化できているかと思います！

2016-10-20 10:11 UTC, YasuomiTakano commented on spec/edinet/financial_information_spec.rb
> +               :context_duration=>"CurrentYearDuration",
これを行なうために、
https://github.com/YasuomiTakano/litexbrl/pull/9#discussion_r84202897
個々の指摘で `context_hash` をモデル化しておく必要があるということでしょうか？

2016-10-21 01:42 UTC, suthio commented on spec/edinet/financial_information_spec.rb
> +               :context_duration=>"CurrentYearDuration",
モデル化する必要はないです！

2016-10-21 01:43 UTC, suthio commented on lib/litexbrl/edinet/financial_information.rb
> +        def duration_judgment(season)
private methodでいいかも

2016-10-21 05:56 UTC, nishaya commented on lib/litexbrl/edinet/financial_information.rb
>            {
@YasuomiTakano 本PRではMUSTじゃないけど、ハッシュは後から要素の追加が可能、モデル(ClassやStruct)は要素が固定されるので、要素の数が可変か固定かで使いわけできるといいね

2016-10-21 05:58 UTC, nishaya requested changes

2016-10-21 05:58 UTC, nishaya commented on lib/litexbrl/edinet/financial_information.rb
> +        def period_judgment(season)
これもprivate

2016-10-24 03:58 UTC, nishaya requested changes

2016-10-24 03:58 UTC, nishaya commented on lib/litexbrl/edinet/financial_information.rb
> +        private
@YasuomiTakano 
`private` は一旦定義すれば以降に全て適用されるので、一回でOKです

2016-10-24 06:30 UTC, YasuomiTakano commented on lib/litexbrl/edinet/financial_information.rb
> +        private
@nishaya 
> `private` は一旦定義すれば以降に全て適用される
ココは知ってます！

であれば、もともとこの行で`private`であったということですよね？
https://github.com/YasuomiTakano/litexbrl/blob/duration_judgment_edit/lib/litexbrl/edinet/financial_information.rb#L9

追加した2つの`private`は削除いたします。

2016-10-24 08:06 UTC, suthio commented
![寿司ゆき:yes](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/01.png)

2016-10-24 08:07 UTC, merged